# NumPy

- NumPy은 Numerical Python의 약자
- 수치형 데이터 연산과 관련된 풍부한 기능을 제공
- 배열에 있는 여러개 값을 반복문을 사용하지 않고 빠른 속도로 연산을 처리하여 결과값을 반환하는 특징있음

In [1]:
!pip install Numpy

In [2]:
import numpy as np

In [6]:
# 3개 정수가 있는 리스트로 배열 생성하기
list1 = [1, 2, 3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [7]:
# np.zeros()를 사용하여 0으로 초기화된 배열을 생성 가능

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
# (2, 3)튜플을 사용해 0으로 초기화된 2차원 배열을 생성

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# np.ones() : np.zeros()와 유사하게 1로 초기된 배열을 생성하는 함수

np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

## 배열 만들기

In [10]:
# np.arrange()
# 파이썬의 기본 내장 함수인 range()와 유사하게 연손된 숫자를 채워서 배열을 생성시켜 줌
# 끝 번호는 반드시 작성해야 하는 입력 인자이고, 시작 번호와 건너뛰는 수는 옵션

# 기본적으로 시작번호는 0으로, 건너뛰는 수는 1로 설정 됨
# range()와 마찬가지로 끝번호 미만의 숫자까지 생성 됨

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(20, 30, 2)

array([20, 22, 24, 26, 28])

In [12]:
np.arange(30, 80, 2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70, 72, 74, 76, 78])

In [16]:
# np.random.rand()
# 정해진 숫자가 아닌 랜덤값으로 배열을 생성

np.random.rand(1, 2, 3, 4)

array([[[[0.01753965, 0.50996703, 0.82986861, 0.37986027],
         [0.01216404, 0.87965351, 0.06586825, 0.39975608],
         [0.12094934, 0.3753305 , 0.30276552, 0.71918948]],

        [[0.72310243, 0.77514935, 0.52875666, 0.38121525],
         [0.8352264 , 0.80253915, 0.08437636, 0.814029  ],
         [0.22103978, 0.97917331, 0.65860663, 0.5490432 ]]]])

### 배열 만들기 : random

In [22]:
# random 메소드에 입력값으로 5를 입력해주면 0에서 1사이의 무작위의 수 5개를 생성

ary = np.random.random(5)
print(ary)                   # 리스트 형태로 출력
print(np.all(ary >= 0.3))    # all() : 배열의 모든 원소가 조건을 만족하면 True를 출력, 그렇지 않으면 False를 출력
print(np.any(ary > 0.7))     # any() : 배열에 조건을 만족하는 원소가 있으면 True를 출력

[0.43379389 0.790585   0.59835352 0.00101444 0.83893171]
False
True


In [23]:
# reshape() : 1차원 배열을 만들고, 차원을 변형하는 방법
# 16개의 값이 들어있는 배열을 (4,4) 형태의 2차원 배열로 변형

arr2 = np.arange(16)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
# 16개의 값이 들어있는 배열을 (2,2,4)형태의 3차원 배열로 변형

arr2.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [27]:
# 0~9 숫자가 담긴 arr라는 배열 생성
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# shape() : 배열의 형태 확인
arr.shape

(10,)

In [30]:
# dtype() : 배열의 데이터 자료형 확인
arr.dtype

dtype('int32')

In [32]:
# astype : 배열의 데이터를 실수형으로 변환 / 소수점이 붙어있는 실수형으로 변환
arr.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])