## 1. 배열이란?
### NumPy 설치하기

In [1]:
!pip install numpy

## 2. 배열 만들기

### np.array()
#### 3개 정수가 있는 리스트로 배열 생성하기

In [3]:
import numpy as np

list1 = [1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

### np.zeros()

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros(25)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((100,200))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### np.ones()

In [9]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones(5000)

array([1., 1., 1., ..., 1., 1., 1.])

### np.empty()

In [13]:
np.empty(5)

array([0., 0., 0., 0., 0.])

### np.arrange()

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
np.arange(500)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [17]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [19]:
# range와 같은 의미, 100~1000이하의 숫자를 의미
np.arange(100, 1000, 5)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195, 200, 205, 210, 215, 220, 225,
       230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290,
       295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345, 350, 355,
       360, 365, 370, 375, 380, 385, 390, 395, 400, 405, 410, 415, 420,
       425, 430, 435, 440, 445, 450, 455, 460, 465, 470, 475, 480, 485,
       490, 495, 500, 505, 510, 515, 520, 525, 530, 535, 540, 545, 550,
       555, 560, 565, 570, 575, 580, 585, 590, 595, 600, 605, 610, 615,
       620, 625, 630, 635, 640, 645, 650, 655, 660, 665, 670, 675, 680,
       685, 690, 695, 700, 705, 710, 715, 720, 725, 730, 735, 740, 745,
       750, 755, 760, 765, 770, 775, 780, 785, 790, 795, 800, 805, 810,
       815, 820, 825, 830, 835, 840, 845, 850, 855, 860, 865, 870, 875,
       880, 885, 890, 895, 900, 905, 910, 915, 920, 925, 930, 935, 940,
       945, 950, 955, 960, 965, 970, 975, 980, 985, 990, 995])

### np.random.rand()

In [21]:
# 정해진 숫자가 아닌 랜덤값으로 배열을 생성
np.random.rand(2,3)

array([[0.79141242, 0.47294339, 0.66332059],
       [0.92337328, 0.28855451, 0.94877418]])

In [ ]:
np.random.rand(2,3)

In [25]:
np.random.rand(100,200)

array([[0.08174319, 0.85528072, 0.40821684, ..., 0.04311531, 0.84907497,
        0.20020995],
       [0.83389615, 0.94973195, 0.87616578, ..., 0.84897656, 0.12452908,
        0.92629829],
       [0.22838554, 0.38451155, 0.34979854, ..., 0.20660347, 0.99189993,
        0.91790653],
       ...,
       [0.39727771, 0.03053941, 0.99538522, ..., 0.43241344, 0.85429048,
        0.50533538],
       [0.13481735, 0.46800694, 0.51487857, ..., 0.72739634, 0.79522295,
        0.16934463],
       [0.48144541, 0.85356756, 0.92794804, ..., 0.03889782, 0.07882634,
        0.95290971]])

In [28]:
np.random.rand(100,200,2)

array([[[0.72087247, 0.20541081],
        [0.44138508, 0.61612305],
        [0.59256151, 0.64434948],
        ...,
        [0.05493868, 0.46326697],
        [0.31570259, 0.11153776],
        [0.25608228, 0.05616524]],

       [[0.93091013, 0.56058041],
        [0.65979144, 0.93184928],
        [0.85035157, 0.23901207],
        ...,
        [0.31155619, 0.31105673],
        [0.33287214, 0.72649999],
        [0.4078953 , 0.3444293 ]],

       [[0.71075579, 0.99089607],
        [0.14533574, 0.5353919 ],
        [0.21608192, 0.46679942],
        ...,
        [0.53538277, 0.86374038],
        [0.8705075 , 0.29735266],
        [0.11695557, 0.93562319]],

       ...,

       [[0.5073479 , 0.87704686],
        [0.99557625, 0.82970755],
        [0.26856666, 0.15298717],
        ...,
        [0.25346707, 0.15979966],
        [0.42848271, 0.71573602],
        [0.38603471, 0.45416725]],

       [[0.30457645, 0.1198384 ],
        [0.20549146, 0.99240609],
        [0.90558752, 0.2632719 ],
        .

In [32]:
np.random.rand(100,200,2,3)

array([[[[0.71077438, 0.12281373, 0.75601471],
         [0.10136349, 0.92659517, 0.49873813]],

        [[0.77591664, 0.83760993, 0.48157692],
         [0.65579519, 0.87603241, 0.75383708]],

        [[0.78517125, 0.30739917, 0.17278445],
         [0.99260849, 0.47167533, 0.60184924]],

        ...,

        [[0.57615762, 0.06918893, 0.07924412],
         [0.60600442, 0.20761702, 0.7250725 ]],

        [[0.75301385, 0.66603535, 0.74257544],
         [0.00442961, 0.82172221, 0.46064462]],

        [[0.1925047 , 0.60100353, 0.28768614],
         [0.44403778, 0.53977674, 0.71249636]]],


       [[[0.85354999, 0.66412377, 0.84503822],
         [0.08953722, 0.44090195, 0.00668853]],

        [[0.40800768, 0.4177587 , 0.22665289],
         [0.93718358, 0.09779095, 0.16217811]],

        [[0.32922344, 0.5769956 , 0.56344596],
         [0.90419261, 0.55234501, 0.1301358 ]],

        ...,

        [[0.77918389, 0.49809205, 0.4794155 ],
         [0.63611951, 0.46373096, 0.78950725]],

        [[

In [23]:
# random 메소드에 입력값으로 5를 입력해주면 0에서 1사이의 무작위의 수 5개를 생성
# print() : 리스트의 형태로 출력
# all() : 배열의 모든 원소가 조건을 만족하면 True를 출력, 그렇지 않으면 False를 출력
# any() : 배열에 조건을 만족하는 원소가 있으면 True를 출력

ary = np.random.rand(5)
print(ary)
print(np.all(ary >= 0.3))
print(np.any(ary > 0.7))

[0.79190125 0.24039724 0.25869825 0.00181775 0.28319415]
False
True


### np.reshape()

In [36]:
arr2 = np.arange(16)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
# 1차원 배열을 3차원으로 변형
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
arr3 = np.arange(100)
arr3.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [41]:
arr3 = np.arange(1000)
arr3.reshape(10,10,10)

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [49]:
# 16개 값이 들어가는 배열을 (2,2,4)형태의 배열로 변형  = (2, 2, 4) 의미 : 2개, 2행, 4열  
arr2.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [53]:
arr2.reshape(2,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

### shape, dtype(), astype()

In [54]:
arr = np.arange(10)

In [59]:
# 배열의 형태 확인
arr.shape

(10,)

In [60]:
# 배열의 데이터 타입 확인
arr.dtype

dtype('int32')

In [58]:
# 배열의 데이터 자료형 확인
arr.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### zeros(), mean(), shape속성

In [61]:
x = np.array([1, 3, 5])
print(x.mean())    # 배열에 저장된 원소들의 평균값을 계산

3.0


In [62]:
print(x.shape)  

(3,)


### array(), reshape()

In [63]:
# Numpy 형식으로 배열의 원소를 입력할 때는 반드시 리스트 형식으로 입력
x = np.array([1, 3, 5])

In [64]:
# 배열을 원하는 모양으로 생성
x = np.array([1,3,4,7,9])
print(x)

[1 3 4 7 9]


### ones()

In [72]:
y = np.ones([3, 4])
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
x = np.array([[1,3,5], [2,4,6]])

In [68]:
x[1]

array([2, 4, 6])

In [69]:
x[1].mean()

4.0

In [70]:
x.mean()

3.5

In [71]:
x.shape

(2, 3)

In [73]:
# 배열도 리스트와 마찬가지로 인덱스를 사용하여 원하는 값을 선택 가능
# 마이너스 인덱스, 콜론(:)을 사용한 인덱스 범위 지정 역시 가능

In [74]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [75]:
# 기본 인덱스
arr[5]

5

In [76]:
# 마이너스 인덱스
arr[-1]

15

In [77]:
# 인덱스 범위
arr[5:8]

array([5, 6, 7])

### 기본 인덱스
- 인덱스를 사용하여 값을 선택하고, 해당 선택한 값에 새로운 값을 할당할 수 있음

In [78]:
# 값 할당
arr[5] = 100
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [79]:
# 여러 값 할당
arr[6:8] = [200, 201]
arr

array([  0,   1,   2,   3,   4, 100, 200, 201,   8,   9,  10,  11,  12,
        13,  14,  15])

### 불리언 인덱스
- 불리언 인덱스는 특정 조건을 만족하는 값을 선택(필터링)할 때 많이 사용

In [85]:
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [86]:
score_arr >= 90

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [87]:
score_arr[score_arr >= 90] 

array([90, 95, 90])

In [88]:
# 90점 이상의 점수를 999점으로 변경하면 결과가 바뀜
score_arr[score_arr >= 90] = 999
score_arr

array([ 80, 999,  70,  65,  85, 999, 999,  80,  75,  80])

### 메서드 체인
- 여러 개의 메서드를 연속해서 이어서 호출하는 것

In [92]:
# 불리언 : Numpy 배열 a의 우너소들이 50을 초과하는지 검사
# 초과하면 True 값을, 초과하지 않으면 False 값을 배열 b에 순서대로 저장

a = np.array([10, 20, 30, 40, 50, 60, 70])
b = a > 50
print(b)

[False False False False False  True  True]


## 인덱싱

In [95]:
# 인덱싱
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x[1])
print(x[:, 1])

[4 5 6]
[2 5 8]


In [100]:
# 2개의 Numpy 배열 간의 계산
x = np.array([[1,2,3], [4,5,6,], [7,8,9]])
y = np.array([[2,3,4], [5,6,7], [8,9,10]])
print(x[:,1]+y[:,1])

[ 5 11 17]


In [101]:
# 리스트 인덱싱
a = np.array([10, 20, 30, 40, 50, 60, 70])
i = [1, 3, 5]
print(a[i])

[20 40 60]


- 파이썬의 2차원 리스트에서 모든 원소의 두번째 원소들만 출력

In [104]:
# 각각의 원소의 특정 인덱스 위치에 일괄적으로 접근 가능
# 먼저 리스트를 Numpy형식으로 변환 후 슬라이싱 해야함
# 리스트의 인덱스는 반드시 정수나 슬라이드여야 함

list1 = [[1, 11], [2, 12], [3, 13]]
np_ary = np.array(list1)
print(np_ary[:, 1])

[11 12 13]


In [115]:
list2 = [[2, 222], [3, 333], [4, 444]]
np_ary2 = np.array(list2)
print(np_ary2[:, 1][2])

444


In [116]:
# 오류를 방지하기 위해 Numpy형태의 배열 a에서 리스트 b로 복사하기 전에 리스트 b 또한 Numpy형태로 변환한 후 복사해야함

a = np.array([10, 20, 30, 40, 50, 60, 70])
b = np.array(a[1:6:2])    
print('b:', b)

b: [20 40 60]


In [119]:
b[1] = 10
print('b:', b)
print('a:', a)
type(b)

b: [20 10 60]
a: [10 20 30 40 50 60 70]


numpy.ndarray

In [125]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130])
b = np.array(a[2:8:2][1])
print(b)

50


### 연산
- 기본 사칙 연산
- 1차원 배열 array([1,2,3,4,5])을 만들어서 각 배열의 원소에 더하기와 곱하기 연산을 해보자

In [130]:
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [131]:
arr + 2

array([3, 4, 5, 6])

In [132]:
arr * 2

array([2, 4, 6, 8])

In [141]:
arr / 2

array([0.5, 1. , 1.5, 2. ])

In [153]:
arr2 = np.arange(2, 6)   
arr2

array([2, 3, 4, 5])

In [154]:
arr + arr2  # 배열과 배열이 같아야 값이 출력된다

array([3, 5, 7, 9])

In [155]:
# 리스트의 경우 리스트와 정수형 데이터와의 더하기 연산은 불가능
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [159]:
# 곱하기 연산의 경우, 값에 적용되는 것이 아니라 리스트 전체를 복사하는 형태로 처리 됨
list = list * 2
list

[1, 2, 3, 4, 1, 2, 3, 4]

In [168]:
# 또 다른 배열 array([5,6,7,8])을 만들어서 배열과 배열 간의 덧셈 연산을 수행
arr1 = np.arange(5, 9)
arr1

array([5, 6, 7, 8])

In [169]:
arr + arr1

array([ 6,  8, 10, 12])

- NumPy에서 제공하는 주요 산술 연산 함수

In [160]:
# 제곱
np.square(arr)

array([ 1,  4,  9, 16], dtype=int32)

In [162]:
# 제곱근(루트)
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [163]:
# exp(지수승)
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [164]:
# log
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [170]:
# 더하기
np.add(arr, arr1)

array([ 6,  8, 10, 12])

In [166]:
# 합계
np.sum(arr)

10

In [167]:
# 누적합
np.cumsum(arr)

array([ 1,  3,  6, 10], dtype=int32)

In [171]:
# 평균
np.mean(arr)

2.5

In [172]:
# 편차
np.var(arr)

1.25

In [173]:
# 표준편차
np.std(arr)

1.118033988749895

In [174]:
#최소값
np.min(arr)

1

In [175]:
#최대값
np.max(arr)

4

In [176]:
#최소값의 인덱스
np.argmin(arr)

0

In [177]:
#최대값의 인덱스
np.argmax(arr)

3

- 2개 배열에 대한 연산

In [180]:
# 2개 배열에 저장된 내용을 인덱스별로 계산
# 선형대수학의 사칙연산과 동일하게 작동
# 곱셈도 같은 원리로 동작

x = np.array([1,2,3])
y = np.array([4,5,6])
z = x * y
print(z)

[ 4 10 18]


In [181]:
# 곱하기
x * y

array([ 4, 10, 18])

In [182]:
# 나누기
x / y

array([0.25, 0.4 , 0.5 ])

In [183]:
z = x * y
print(z)

[ 4 10 18]


### 변형 (Trandspose)
- 기존에 있는 배열의 축을 바꾸는 방법으로 사용

In [188]:
#첫번째 행(row)에 있는 값들이 첫번째 열(column)에 위치하고, 
# 두번째 행에 있는 값들이 두번째 열에 위치하도록 변환

arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [190]:
# transpose() 호출 시 축을 지정하지 않을 경우

arr.T      #arr.transpose()와 동일

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [191]:
# 3차원의 축배열
arr3d = np.arange(27).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [194]:
arr3d.transpose()     # transpose(2,1,0)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [195]:
arr3d.transpose(1,0,2)

array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]])

### 제로 벡터와 제로 행렬

In [196]:
# 0으로 초기화된 1차원의 zero_vector 생성
zero_vector = np.zeros(3)
print(zero_vector)

[0. 0. 0.]


In [197]:
# 0으로 초기화된 (4X3)형식의 2차원 배열 생성 
zero_matrix = np.zeros((4,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [199]:
# 0의 값을 갖는 5개의 1차원 배열 생성
zero_vector = np.zeros(5)
zero_vector

array([0., 0., 0., 0., 0.])

In [201]:
# 모든 원소의 값이 0인 (5x3) 형식의 2차원 배열 생성
zero_matrix = np.zeros((5,3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [202]:
# 생성한 제로 벡터나 행렬에 새로운 값으로 다시 재설정
my_array = np.zeros(15).reshape(3, 5)
my_array += 4
my_array

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

### 전치 행렬

In [203]:
# transpose()

ary = np.array([[1,2], [3,4]])
print(ary.transpose())

[[1 3]
 [2 4]]


### 저장
- Numpy의 save()함수의 확장자 '.npy'

In [205]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [206]:
np.save('array', arr)

In [207]:
#코드와 같은 디렉토리에 array.npy 라는 파일이 생성된 것을 확인
# 생성한 파일을 np.load()를 사용하여 불러오고, load_arr라는 변수에 담기

load_arr = np.load('array.npy')
load_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])